name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  # Update Node.js dependencies
  update-frontend-deps:
    name: Update Frontend Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Update dependencies
      run: |
        cd frontend
        npm update
        npm audit fix --force

    - name: Run tests
      run: |
        cd frontend
        npm run lint
        npm run build

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update frontend dependencies'
        title: '🔄 Auto-update frontend dependencies'
        body: |
          This PR updates frontend dependencies to their latest versions.
          
          **Changes:**
          - Updated Node.js packages
          - Applied security fixes via `npm audit fix`
          
          **Testing:**
          - ✅ Linting passed
          - ✅ Build successful
          
          Please review the changes and ensure all tests pass before merging.
        branch: chore/update-frontend-deps
        delete-branch: true

  # Update Python dependencies
  update-backend-deps:
    name: Update Backend Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools safety

    - name: Update dependencies
      run: |
        cd backend
        pip-compile --upgrade requirements.in
        safety check

    - name: Run basic tests
      run: |
        cd backend
        pip install -r requirements.txt
        python -m pytest tests/ -x --tb=short

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update backend dependencies'
        title: '🔄 Auto-update backend dependencies'
        body: |
          This PR updates backend dependencies to their latest versions.
          
          **Changes:**
          - Updated Python packages
          - Verified security with safety check
          
          **Testing:**
          - ✅ Security scan passed
          - ✅ Basic tests passed
          
          Please review the changes and run full test suite before merging.
        branch: chore/update-backend-deps
        delete-branch: true
